---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: website-service
spec:
   selector:
      matchLabels:
         app: website-service
   replicas: 1
   template:
      metadata:
         labels:
            app: website-service
      spec:
         imagePullSecrets:
         - name: secretname
         containers:
         - name: website-service
           image: chrissiddall.azurecr.io/ncreactportfoliowebsite:latest
           imagePullPolicy: Always
           resources:
           ports:
           - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
   name: website-service
spec:
   selector:
      app: website-service
   type: LoadBalancer
   ports:
      - port: 80
...